WarmUp/WarmUp/Models/ErrorViewModel.cs
using System;

namespace WarmUp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WarmUp/WarmUp/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace WarmUp.Models
{
    public partial class Post
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Título no puede estar vacío")]
        [DisplayName("Título")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "Contenido no puede estar vacío")]
        public string Contenido { get; set; }
        public string Imagen { get; set; }
        [Required]
        [DisplayName("Fecha de creación")]
        [DataType(DataType.Date)]
        public DateTime FechaCreacion { get; set; }
        
        [Required(ErrorMessage = "Categoría no puede estar vacío")]
        public string Categoría { get; set; }
    }
}

WarmUp/WarmUp/Models/Warm_Up_ChallengeContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace WarmUp.Models
{
    public partial class Warm_Up_ChallengeContext : DbContext
    {
        public Warm_Up_ChallengeContext()
        {
        }

        public Warm_Up_ChallengeContext(DbContextOptions<Warm_Up_ChallengeContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Server=DESKTOP-DMR2OKH\\LOCAL;Database=Warm_Up_Challenge;Integrated Security=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Post>(entity =>
            {
                entity.Property(e => e.Categoría)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Contenido)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.FechaCreacion)
                    .HasColumnType("date")
                    .HasColumnName("Fecha_creacion");

                entity.Property(e => e.Imagen)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Titulo)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

WarmUp/WarmUp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WarmUp.Models;

namespace WarmUp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WarmUp/WarmUp/Controllers/PostsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WarmUp.Models;

namespace WarmUp.Controllers
{
    
    public class PostsController : Controller
    {
        public readonly Warm_Up_ChallengeContext db;

        public PostsController(Warm_Up_ChallengeContext context)
        {
            db = context;
        }

        //GET
        
        public IActionResult Index()
        {
            var Posts = db.Posts.ToList();
            Posts.Sort((x, y)=> y.FechaCreacion.CompareTo(x.FechaCreacion));
            return View(Posts);
        }

        //Get-Details
        [Route("/{controller}/{id:int}")]
        public IActionResult Details(int? id)
        {
            var consulta = db.Posts.Where(p => p.Id == id).Count();
            if (consulta == 0)
            {
                return NotFound();
            }
            else
            {
                var post = db.Posts.Where(p => p.Id == id).FirstOrDefault();
                return View(post);
            }
        }

        //GET-Create
        [Route("/{controller}")]
        public IActionResult Create()
        {
            return View();
        }

        //GET-Delete
        
        public IActionResult Delete(int? id)
        {
            
            if (id == null || id == 0)
            {
                return NotFound();
            }
            else
            {
                var obj = db.Posts.Where(p => p.Id == id).FirstOrDefault();
                return View(obj);
            }
        }

        //GET-Update
        public IActionResult Update(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            else
            {
                var obj = db.Posts.Where(p => p.Id == id).FirstOrDefault();
                return View(obj);
            }
        }

        //POST-Create
        [HttpPost]
        [Route("/{controller}/")]
        public IActionResult Create(Post obj)
        {
            obj.FechaCreacion = DateTime.Now;
            db.Posts.Add(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //POST-Delete
        [HttpPost]
        public IActionResult DeletePost(int id)
        {
            var post = db.Posts.Where(p => p.Id == id).Count();
            if (post == 0)
            {
                return NotFound();
            }
            else
            {
                var delPost = db.Posts.Where(p => p.Id == id).FirstOrDefault();
                db.Posts.Remove(delPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        //POST-Update
        [HttpPost]
        public IActionResult Update(Post obj)
        {
            obj.FechaCreacion = DateTime.Now;
            db.Posts.Update(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WarmUp/WarmUp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WarmUp/WarmUp/Views/Posts/Create.cshtml
@model WarmUp.Models.Post

@{
    ViewData["Title"] = "Crear Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Nuevo post</h1>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control"  />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoría" class="control-label"></label>
                <input asp-for="Categoría" class="form-control" />
                <span asp-validation-for="Categoría" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contenido" class="control-label"></label>
                <textarea id="Contenido" asp-for="Contenido" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Contenido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label">Url de imagen - (opcional)</label>
                <input asp-for="Imagen"  class="form-control" type="text" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear post" class="btn btn-success" /> |
                <a asp-action="Index" class="btn btn-info">Volver a inicio</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WarmUp/WarmUp/Views/Posts/Delete.cshtml
@model WarmUp.Models.Post

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
     Estás <strong> seguro </strong>de querer eliminar este post?
</h2>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Categoría)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Categoría)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Contenido)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contenido)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(model => model.Imagen)" alt="Imagen" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>
    </dl>

    <form asp-action="DeletePost">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-info">Volver a Inicio</a>
    </form>
</div>

WarmUp/WarmUp/Views/Posts/Details.cshtml
@model WarmUp.Models.Post

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalles</h1>

<div>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Titulo)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Titulo)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Categoría)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Categoría)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Contenido)
                    </dt>
                    <dd class="col-sm-10" >
                        @Html.DisplayFor(model => model.Contenido)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Imagen)
                    </dt>
                    <dd class="col-sm-8">
                        <img src="@Html.DisplayFor(model => model.Imagen)" alt="Imagen"/>
                    </dd>
                    <dt class="col-sm-10">
                        @Html.DisplayNameFor(model => model.FechaCreacion)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.FechaCreacion)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
    
</div>
<div>
    <a asp-action="Index" class="btn btn-info">Atrás</a>
</div>

WarmUp/WarmUp/Views/Posts/Index.cshtml
@model IEnumerable<WarmUp.Models.Post>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col">
            <h1 style="text-align:center">Challenge Warm Up</h1>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <h3>Lista de Posts</h3>
    </div>
</div>
    

<table class="table table-bordered">
    <thead style="background-color: dimgrey; text-align: center">
        <tr style="color: white">
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td style="text-align: center">
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Detalles</a> |
                <a asp-action="Update" asp-route-id="@item.Id" class="btn btn-primary">Editar</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

WarmUp/WarmUp/Views/Posts/Update.cshtml
@model WarmUp.Models.Post

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar post</h1>

<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Update">
            <input asp-for="Id" hidden />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Categoría" class="control-label"></label>
                <input asp-for="Categoría" class="form-control" />
                <span asp-validation-for="Categoría" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Contenido" class="control-label"></label>
                <textarea asp-for="Contenido" class="form-control" rows="5"> </textarea>
                <span asp-validation-for="Contenido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label">Url de imagen - (opcional)</label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" /> |
                <a asp-action="Index" class="btn btn-info">Volver a inicio</a>
            </div>
        </form>
    </div>
</div>



WarmUp/WarmUp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WarmUp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">WarmUp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Index">Inicio</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Create">Nuevo post</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WarmUp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>